### ISSUE TITLE
error with alias when babel installed

### ISSUE THREAD

**Issue by funkyduke** [mikrobi/babel#112] opened 2015-05-27 19:08 UTC
For example: if you have a context that is called "fr" and when you give a resource in the main-context (web) the alias starting with fr (f.e.: www.test.com/freakout) then you get a 503 error.

**Comment by goldsky** [comment] 2016-01-18 19:44
I think the problem is in .htaccess

**Comment by vierkantemeter** [comment] 2016-01-20 09:39
I've tested this, and I can confirm this problem. Don't know yet what the problem is.

**Comment by joyceDesignbase** [comment] 2016-02-15 13:33
Same problem here.

**Comment by degoya** [comment] 2016-02-15 14:48
i've got the same problem on a nginx server with babel beta4 on modx 2.3.6.
I use the following rewrite:

    try_files $uri $uri/ /index.php?cultureKey=$1&q=404-error;
    rewrite ^/(en|de)/css(.*)$ /css$2 break;
    rewrite ^/(en|de)/js(.*)$ /js$2 break;
    rewrite ^/(en|de)/img(.*)$ /img$2 break;
    rewrite ^/(en|de)/assets(.*)$ /assets$2 break;
    rewrite ^/(en|de)/fonts(.*)$ /fonts$2 break;
    rewrite ^/(en|de)/theme(.*)$ /theme$2 break;
    rewrite ^/(en|de)/content(.*)$ /content$2 break;
    if (!-e $request_filename){
        rewrite ^/(en|de)?/?(.*)$ /index.php?cultureKey=$1&q=$2 last;
    }

**Comment by goldsky** [comment] 2016-02-15 15:07
Which redirect plugin are you using?
My testing doesn't seem breaking.
http://babel.virtudraft.com/en/english.html
http://babel.virtudraft.com/de/deutsche.html

**Comment by joyceDesignbase** [comment] 2016-02-15 15:22
I'm using the plugin described in step 4 on http://www.multilingual-modx.com/blog/2011/multilingual-websites-with-modx-and-babel.html. (modx 2.4.2, babel 3.0.0-beta4)

this is not a problem: http://babel.virtudraft.com/de/deutsche.html
but this breaks: http://babel.virtudraft.com/deutsche.html (because the page starts with de)

**Comment by goldsky** [comment] 2016-02-15 15:25
of course, but it's 404, not 503 as OP.

Even http://babel.virtudraft.com/en/profile.html if you go to http://babel.virtudraft.com/profile.html you'll get 404. What do you expect?

**Comment by goldsky** [comment] 2016-02-15 15:34
this is my htaccess https://gist.github.com/goldsky/e4b3ce824acc6fd25ca8
my server actually runs on nginx, which reads htaccess

I'm using the edited [XRouting](https://modx.com/extras/package/xrouting)
@chsmedien will update the edit for upcoming release.
https://gist.github.com/goldsky/e926167132e227e2f10f

**Comment by joyceDesignbase** [comment] 2016-02-15 16:10
Ok sorry, i explained it wrong :). 
I meant that any url containing for example www.mywebsite.com/en/english.html or www.mywebsite.com/de/deutsch.html is no problem for me either, but in the default context if i have a page that starts with 'en' or 'de' it will give 503 error. 
So www.mywebsite.com/entourage.html or www.mywebsite.com/deviation.html will give 503, same as funkyduke.

I will try the XRouting and your htaccess

**Comment by degoya** [comment] 2016-02-15 16:13
my plugin looks like this 

    <?php
    if($modx->context->get('key') != "mgr"){
        /* set plugin on OnHandleRequest - grab the current langauge from the cultureKey request var */
        switch ($_REQUEST['cultureKey']) {
            case 'de':
                /* switch the context */
                $modx->switchContext('de');
                break;
            case 'en':
                /* switch the context */
                $modx->switchContext('en');
                break;
            default:
                /* Set the default context here */
                $modx->switchContext('de');
                break;
        }
        /* unset GET var to avoid
         * appending cultureKey=xy to URLs by other components */
        unset($_GET['cultureKey']);
    }

**Comment by degoya** [comment] 2016-02-15 16:15
btw. how you manage to read .htaccess by nginx? could you ponit me to a source?

**Comment by goldsky** [comment] 2016-02-15 16:26
We have an easy path.
We are using VPS, and using CentOS.
For control panel, we picked [CentOS Web Panel](http://centos-webpanel.com/)

![webservers](https://cloud.githubusercontent.com/assets/308524/13054174/d60ba302-d43a-11e5-818f-29ad28d7b69f.png)

This has feature to set which webserver we could use, so we set "Apache & Nginx Reverse Proxy"
It'll generate all *.conf files automagically.

**Comment by goldsky** [comment] 2016-02-15 16:27
I think other control panels provide similar features.
Well, on VPS+ of course

**Comment by goldsky** [comment] 2016-02-15 16:38
@joyceDesignbase , download the XRouting (for the event selections), but use the code on my gist.
It was fixed by chsmedien himself.

**Comment by goldsky** [comment] 2016-03-22 04:04
I'm closing this issue. If problem persists, please open new one and link this issue.

**Closed by goldsky** 2016-03-22 04:04 UTC
Labels: bug
